language: java
sudo: true
cache:
  directories:
    - $HOME/.m2
script:
  - set -e
  - mvn clean install -Pqulice --errors --batch-mode
  - mvn clean
  - pdd --source=$(pwd) --file=/dev/null
before_install:
  - rvm install 2.2.2
  - rvm use 2.2.2
  - sudo apt-get install texlive-latex-extra
install:
  - gem install pdd
env:
  global:
    - MAVEN_OPTS="-Xmx256m"
    - JAVA_OPTS="-Xmx256m"
jdk:
  - oraclejdk8
after_success:
  - "bash <(curl -s https://codecov.io/bash)"
